name: billionaire
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animations: ^2.0.11
  billion_charts_package:
    path: ./billion_charts_package
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4 
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  fuzzy: ^0.5.1
  # gaimon: ^1.4.1
  go_router: ^15.1.3
  # haptic_feedback: ^0.5.1+1
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  pinput: ^5.0.1
  riverpod_annotation: ^2.6.1
  sensors_plus: ^6.1.1
  shake: ^3.0.0
  shared_preferences: ^2.5.3
  spoiler_widget: ^1.0.12
  sqlite3_flutter_libs: ^0.5.34
  vibration: ^3.1.3
  worker_manager: ^7.2.6

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  drift_dev: ^2.27.0
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - .env
    
flutter_gen:
  output: lib/core/gen/ 
  line_length: 80 

  integrations:
    image: true
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
