name: billionaire
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  sensors_plus: ^6.1.1
  shake: ^3.0.0
  spoiler_widget: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.10.0
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/core/gen/ 
  line_length: 80 

  integrations:
    image: true
    flutter_svg: true